# Synopsis: Generate markdown docs for Public/Private functions.

function Get-RepoDocsFunctionHelp {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string] $FilePath
    )

    $raw = Get-Content -Raw -Path $FilePath
    $tokens = $null
    $parseErrors = $null

    $ast = [System.Management.Automation.Language.Parser]::ParseInput($raw, [ref] $tokens, [ref] $parseErrors)

    if ($parseErrors -and $parseErrors.Count -gt 0)
    {
        throw "Failed to parse '$FilePath': $($parseErrors[0].Message)"
    }

    $functionAsts = $ast.FindAll({
            param($node)
            $node -is [System.Management.Automation.Language.FunctionDefinitionAst]
        }, $true)

    foreach ($functionAst in $functionAsts)
    {
        $help = $functionAst.GetHelpContent()

        $paramAsts = @()
        if ($functionAst.Body -and $functionAst.Body.ParamBlock)
        {
            $paramAsts = $functionAst.Body.ParamBlock.Parameters
        }

        $paramInfos = foreach ($paramAst in $paramAsts)
        {
            $paramName = $paramAst.Name.VariablePath.ToString()

            $paramAttribute = $paramAst.Attributes |
                Where-Object { $_.TypeName.FullName -eq 'Parameter' } |
                Select-Object -First 1

            $mandatory = $false
            $pipeline = $false

            if ($paramAttribute)
            {
                foreach ($arg in $paramAttribute.NamedArguments)
                {
                    if ($arg.ArgumentName -in @('Mandatory', 'ValueFromPipeline', 'ValueFromPipelineByPropertyName'))
                    {
                        $value = $arg.Argument.Extent.Text
                        if ($value -match '^\$true$')
                        {
                            switch ($arg.ArgumentName)
                            {
                                'Mandatory' { $mandatory = $true }
                                'ValueFromPipeline' { $pipeline = $true }
                                'ValueFromPipelineByPropertyName' { $pipeline = $true }
                            }
                        }
                    }
                }
            }

            $typeName = ''
            if ($paramAst.StaticType)
            {
                $typeName = $paramAst.StaticType.Name
            }

            $descKey = $paramName.ToUpperInvariant()
            $description = ''
            if ($help -and $help.Parameters -and $help.Parameters.ContainsKey($descKey))
            {
                $description = $help.Parameters.$descKey
            }

            [pscustomobject]@{
                Name        = $paramName
                Type        = $typeName
                Mandatory   = $mandatory
                Pipeline    = $pipeline
                Description = $description
            }
        }

        [pscustomobject]@{
            Name       = $functionAst.Name
            Help       = $help
            Parameters = $paramInfos
        }
    }
}

function Convert-RepoDocsHelpToMarkdown {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string] $Name,

        [Parameter(Mandatory = $true)]
        [string] $SourcePath,

        [Parameter()]
        [object] $Help,

        [Parameter()]
        [object[]] $Parameters = @()
    )

    $md = New-Object System.Text.StringBuilder

    $null = $md.AppendLine('<!-- Generated by build task Generate_Repo_Docs. Do not edit manually. -->')
    $null = $md.AppendLine(("# {0}" -f $Name))
    $null = $md.AppendLine()
    $null = $md.AppendLine(('Source: `{0}`' -f $SourcePath))
    $null = $md.AppendLine()

    $synopsis = $null
    $description = $null
    $examples = @()

    if ($Help)
    {
        $synopsis = $Help.Synopsis
        $description = $Help.Description
        $examples = @($Help.Examples)
    }

    if ($synopsis)
    {
        $null = $md.AppendLine('## Synopsis')
        $null = $md.AppendLine()
        $null = $md.AppendLine($synopsis.TrimEnd())
        $null = $md.AppendLine()
    }

    if ($description)
    {
        $null = $md.AppendLine('## Description')
        $null = $md.AppendLine()
        $null = $md.AppendLine($description.TrimEnd())
        $null = $md.AppendLine()
    }

    if ($Parameters -and $Parameters.Count -gt 0)
    {
        $null = $md.AppendLine('## Parameters')
        $null = $md.AppendLine()
        $null = $md.AppendLine('| Name | Type | Mandatory | Pipeline | Description |')
        $null = $md.AppendLine('| --- | --- | --- | --- | --- |')

        foreach ($p in $Parameters)
        {
            $mandatory = if ($p.Mandatory) { 'Yes' } else { 'No' }
            $pipeline = if ($p.Pipeline) { 'Yes' } else { 'No' }
            $type = if ($p.Type) { $p.Type } else { '' }
            $desc = if ($p.Description) { ($p.Description -replace "\r?\n", ' ') } else { '' }

            # Escape pipe in description so it doesn't break the table.
            $desc = $desc -replace '\|', '\\|'

            $null = $md.AppendLine("| $($p.Name) | $type | $mandatory | $pipeline | $desc |")
        }

        $null = $md.AppendLine()
    }

    if ($examples -and $examples.Count -gt 0)
    {
        $null = $md.AppendLine('## Examples')
        $null = $md.AppendLine()

        $i = 0
        foreach ($ex in $examples)
        {
            if (-not $ex) { continue }
            $i++
            $null = $md.AppendLine(("### Example {0}" -f $i))
            $null = $md.AppendLine()
            $null = $md.AppendLine('```powershell')
            $null = $md.AppendLine($ex.TrimEnd())
            $null = $md.AppendLine('```')
            $null = $md.AppendLine()
        }
    }

    $md.ToString()
}

function Convert-RepoDocsPathToPosix {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string] $Path
    )

    $Path -replace '\\', '/'
}

task Generate_Repo_Docs {
    $repoRoot = (Get-Location).Path
    $sourceRoot = Join-Path -Path $repoRoot -ChildPath 'source'

    $docsRoot = Join-Path -Path $repoRoot -ChildPath 'docs'
    $publicDocs = Join-Path -Path $docsRoot -ChildPath 'Public'
    $privateDocs = Join-Path -Path $docsRoot -ChildPath 'Private'

    $null = New-Item -ItemType Directory -Force -Path $publicDocs
    $null = New-Item -ItemType Directory -Force -Path $privateDocs

    Get-ChildItem -Path $publicDocs -Filter '*.md' -File -ErrorAction SilentlyContinue | Remove-Item -Force
    Get-ChildItem -Path $privateDocs -Filter '*.md' -File -ErrorAction SilentlyContinue | Remove-Item -Force

    $targets = @(
        [pscustomobject]@{ Name = 'Public';  Source = (Join-Path $sourceRoot 'Public');  Out = $publicDocs },
        [pscustomobject]@{ Name = 'Private'; Source = (Join-Path $sourceRoot 'Private'); Out = $privateDocs }
    )

    foreach ($t in $targets)
    {
        if (-not (Test-Path -Path $t.Source))
        {
            continue
        }

        $functions = @()

        foreach ($file in (Get-ChildItem -Path $t.Source -Filter '*.ps1' -File -Recurse))
        {
            foreach ($fn in (Get-RepoDocsFunctionHelp -FilePath $file.FullName))
            {
                $sourceRel = Convert-RepoDocsPathToPosix -Path ($file.FullName.Substring($repoRoot.Length).TrimStart('\\'))
                $sourcePathText = $sourceRel

                $md = Convert-RepoDocsHelpToMarkdown -Name $fn.Name -SourcePath $sourcePathText -Help $fn.Help -Parameters $fn.Parameters

                $outPath = Join-Path -Path $t.Out -ChildPath "$($fn.Name).md"
                Set-Content -Path $outPath -Value $md -Encoding utf8

                $functions += $fn.Name
            }
        }

        $functions = $functions | Sort-Object -Unique

        $index = New-Object System.Text.StringBuilder
        $nl = "`r`n"

        $null = $index.Append("<!-- Generated by build task Generate_Repo_Docs. Do not edit manually. -->$nl")
        $null = $index.Append("# $($t.Name) Functions$nl$nl")

        if ($functions.Count -eq 0)
        {
            $null = $index.Append("No functions found.$nl")
        }
        else
        {
            foreach ($name in $functions)
            {
                $null = $index.Append("- [$name](./$name.md)$nl")
            }
        }

        Set-Content -Path (Join-Path $t.Out 'README.md') -Value $index.ToString() -Encoding utf8
    }
}
