<#
.SYNOPSIS
Imports and connects to a Wi-Fi network using an XML profile.

.DESCRIPTION
Validates the Wi-Fi profile XML (must include WLANProfile.Name and have an
unprotected shared key if present), imports it with netsh, then connects to
the profile SSID.

.PARAMETER WifiProfilePath
Path to a WLANProfile XML file generated by netsh wlan export profile ... key=clear.

.EXAMPLE
Connect-MCDWifiProfile -WifiProfilePath 'D:\\MCD\\Config\\WiFi\\WiFiProfile.xml'

Imports the profile and attempts to connect.
#>
function Connect-MCDWifiProfile
{
    [CmdletBinding(SupportsShouldProcess = $true)]
    [OutputType([bool])]
    param
    (
        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [string]
        $WifiProfilePath
    )

    if (-not (Test-Path -Path $WifiProfilePath))
    {
        throw "Wi-Fi profile not found: $WifiProfilePath"
    }

    [xml]$xml = Get-Content -Path $WifiProfilePath -Raw -ErrorAction Stop
    $ssid = $xml.WLANProfile.Name
    if (-not $ssid)
    {
        throw 'Wi-Fi profile XML is missing WLANProfile.Name.'
    }

    $isProtected = $xml.WLANProfile.MSM.security.sharedKey.protected
    if ($isProtected -and ($isProtected -ne 'false'))
    {
        throw 'Wi-Fi profile XML must contain a plaintext key (protected=false).'
    }

    if (-not $PSCmdlet.ShouldProcess($ssid, "Import Wi-Fi profile and connect"))
    {
        return $false
    }

    Write-MCDLog -Level Info -Message "Importing Wi-Fi profile for SSID '$ssid'."
    netsh wlan delete profile name="$ssid" | Out-Null
    netsh wlan add profile filename="$WifiProfilePath" | Out-Null

    $result = netsh wlan connect name="$ssid"
    if ($result -notmatch 'completed successfully')
    {
        Write-MCDLog -Level Warning -Message "Wi-Fi connect failed for SSID '$ssid': $result"
        return $false
    }

    return $true
}
